#Publishes a package to GitHub Packages when a new tag is made
name: Publish package to GitHub Packages
on:
  push:
    tags:
      - "*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish package
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          ./gradlew -P version=${NEW_VERSION} publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
